# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "ipostnikov/kbot"
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "v1.3.0-e128987"
  tag: "v1.18.0-f22ec0f"
  arch: ""
imagePullSecrets:
  - name: ghcr-secret
secret:
  name: tg-secret
  key: token
  env: TELE_TOKEN
